export const routes = {
  login: '/login',
  passwordReset: '/password-reset',
  dashboard: '/dashboard',
  inventory: '/inventory',
  ledger: '/ledger',
  reservations: '/reservations',
  salesOrders: '/sales-orders',
  adjustments: '/movements/adjustments',
  transfers: '/movements/transfers',
  recommendations: '/procurement/recommendations',
  purchaseOrders: '/procurement/purchase-orders',
  vendorProducts: '/vendor-products',
  users: '/users',
  vendors: '/vendors',
} as const;
